version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PORT=3000
    networks:
      - rcare-network

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rcare-network

networks:
  rcare-network:
    driver: bridge
