version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      GITHUB_TOKEN: ${GITHUB_TOKEN}

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile

    ports:
      - "5173:80"

    depends_on:
      - backend